{
 "title": "Scaphandre Ollama",
 "tags": [
  "scaphandre",
  "energy",
  "power"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "process_filter" }
  ]
 },
 "panels": [
  {
   "title": "Per hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hosts power consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hosts power consumption total (dynamic time range)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Wh" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_host_power_microwatts[1h]))/1000000",
     "legendFormat": "total of hosts, during displayed time window"
    }
   ]
  },
  {
   "title": "Per CPU Sockets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Socket power consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "scaph_socket_power_microwatts / 1000000",
     "legendFormat": "{{instance}} Socket {{socket_id}}"
    }
   ]
  },
  {
   "title": "Ollama Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(scaph_process_power_consumption_microwatts{cmdline=~\".*ollama.*\"}[1h])) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top process consumers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(3, sum by (exe) (scaph_process_power_consumption_microwatts/1000000)))",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Filtered process (process_filter) power, by exe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts{exe=~\".*${process_filter}.*\"}/1000000",
     "legendFormat": "{{ cmdline }}"
    }
   ]
  }
 ]
}